DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email VARCHAR(254) UNIQUE                                 NOT NULL,
    name  VARCHAR(250)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000),
    category_id        BIGINT,
    confirmed_requests INTEGER DEFAULT 0,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT,
    lat                DOUBLE PRECISION,
    lon                DOUBLE PRECISION,
    paid               BOOLEAN DEFAULT false,
    participant_limit  INTEGER DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT true,
    state              VARCHAR(50),
    title              VARCHAR(120),
    views              BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    event_id     BIGINT                                              NOT NULL,
    requester_id BIGINT                                              NOT NULL,
    status       VARCHAR DEFAULT 'PENDING',
    CONSTRAINT UC_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned BOOLEAN DEFAULT FALSE,
    title  VARCHAR(50)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    compilation_id BIGINT                                              NOT NULL,
    event_id       BIGINT                                              NOT NULL,
    CONSTRAINT UC_compilation_event UNIQUE (compilation_id, event_id)
);

-- Внешние ключи
ALTER TABLE events
    ADD FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT;
ALTER TABLE events
    ADD FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE requests
    ADD FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE requests
    ADD FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE compilations_events
    ADD FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE;
ALTER TABLE compilations_events
    ADD FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

-- Индексы для улучшения производительности
CREATE INDEX idx_events_state ON events (state);
CREATE INDEX idx_events_category ON events (category_id);
CREATE INDEX idx_events_initiator ON events (initiator_id);
CREATE INDEX idx_requests_event ON requests (event_id);
CREATE INDEX idx_requests_requester ON requests (requester_id);