DROP TABLE IF EXISTS compilations_events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email VARCHAR(254) UNIQUE                                 NOT NULL,
    name  VARCHAR(250)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000)                                       NOT NULL,
    category_id        BIGINT                                              NOT NULL,
    confirmed_requests INTEGER DEFAULT 0                                   NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       BIGINT                                              NOT NULL,
    lat                DOUBLE PRECISION                                    NOT NULL,
    lon                DOUBLE PRECISION                                    NOT NULL,
    paid               BOOLEAN DEFAULT false                               NOT NULL,
    participant_limit  INTEGER DEFAULT 0                                   NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT true                                NOT NULL,
    state              VARCHAR(50)                                         NOT NULL,
    title              VARCHAR(120)                                        NOT NULL,
    views              BIGINT  DEFAULT 0                                   NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    event_id     BIGINT                                              NOT NULL,
    requester_id BIGINT                                              NOT NULL,
    status       VARCHAR(20) DEFAULT 'PENDING'                       NOT NULL,
    CONSTRAINT UC_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned BOOLEAN DEFAULT FALSE                               NOT NULL,
    title  VARCHAR(50)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    compilation_id BIGINT                                              NOT NULL,
    event_id       BIGINT                                              NOT NULL,
    CONSTRAINT UC_compilation_event UNIQUE (compilation_id, event_id)
);

-- Внешние ключи
ALTER TABLE events
    ADD FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT;
ALTER TABLE events
    ADD FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE participation_requests
    ADD FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE participation_requests
    ADD FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE compilations_events
    ADD FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE;
ALTER TABLE compilations_events
    ADD FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

-- Индексы для улучшения производительности
CREATE INDEX idx_events_state ON events (state);
CREATE INDEX idx_events_category ON events (category_id);
CREATE INDEX idx_events_initiator ON events (initiator_id);
CREATE INDEX idx_events_event_date ON events (event_date);
CREATE INDEX idx_requests_event ON participation_requests (event_id);
CREATE INDEX idx_requests_requester ON participation_requests (requester_id);
CREATE INDEX idx_requests_status ON participation_requests (status);
CREATE INDEX idx_categories_name ON categories (name);
CREATE INDEX idx_users_email ON users (email);